from typing import Protocol, List, Any

class IAchievementRepository(Protocol):
    def get_by_id(self, record_id: int) -> Any: ...
    def get_all(self) -> List[Any]: ...
    def create(self, entity: Any) -> Any: ...
    def delete(self, entity: Any) -> None: ...
    
    def get_user_badges(self, user_id: int) -> List[Any]: ...
    def award_badge(self, user_id: int, achievement_id: int) -> Any: ...
    def has_badge(self, user_id: int, achievement_id: int) -> bool: ...