from typing import Protocol, TypeVar, Optional, List

T = TypeVar("T")

class IBaseRepository(Protocol[T]):
    def get_by_id(self, record_id: int) -> Optional[T]: ...
    def get_all(self) -> List[T]: ...
    def create(self, entity: T) -> T: ...
    def delete(self, entity: T) -> None: ...