from typing import Protocol, Optional, List, Any

class IClassroomRepository(Protocol):
    def get_by_id(self, record_id: int) -> Optional[Any]: ...
    def get_all(self) -> List[Any]: ...
    def create(self, entity: Any) -> Any: ...
    def delete(self, entity: Any) -> None: ...
    
    def get_by_join_code(self, code: str) -> Optional[Any]: ...
    def get_by_teacher(self, teacher_id: int) -> List[Any]: ...
    def create_classroom(self, classroom: Any) -> Any: ...
    def get_classroom_statistics(self, classroom_id: int) -> dict: ...