from typing import Protocol, List, Any

class IEnrollmentRepository(Protocol):
    def get_by_id(self, record_id: int) -> Any: ...
    def get_all(self) -> List[Any]: ...
    def create(self, entity: Any) -> Any: ...
    def delete(self, entity: Any) -> None: ...
    
    def enroll_student(self, user_id: int, classroom_id: int) -> Any: ...
    def is_student_enrolled(self, user_id: int, classroom_id: int) -> bool: ...
    def get_student_classrooms(self, user_id: int) -> List[Any]: ...
    def get_classroom_students(self, classroom_id: int) -> List[Any]: ...