from typing import Protocol, Optional, List, Any

class ILabRepository(Protocol):
    def get_by_id(self, record_id: int) -> Optional[Any]: ...
    def get_all(self) -> List[Any]: ...
    def create(self, entity: Any) -> Any: ...
    def delete(self, entity: Any) -> None: ...
    
    def get_by_lab_id(self, manifest_id: str) -> Optional[Any]: ...
    def get_active_labs(self) -> List[Any]: ...
    def get_by_category(self, category: str) -> List[Any]: ...
    def set_lab_status(self, lab_id: int, status: bool) -> bool: ...
    def activate_lab(self, lab_id: int) -> bool: ...
    def disable_lab(self, lab_id: int) -> bool: ...