from typing import Protocol, Optional, List, Any

class IUserRepository(Protocol):
    def get_by_id(self, record_id: int) -> Optional[Any]: ...
    def get_by_username(self, username: str) -> Optional[Any]: ...
    def create_user(self, user: Any) -> Any: ...
    def increment_xp(self, user_id: int, amount: int) -> Optional[Any]: ...