from typing import Protocol, Optional
from domain.gamification.entities import Badge
from domain.gamification.context import AchievementContext

class IAchievementRule(Protocol):
    def evaluate(self, context: AchievementContext) -> Optional[Badge]: ...

# Repositories accessibles via l'UoW (Protocoles)
class IXPRepository(Protocol):
    def add_xp(self, student_id: int, amount: int) -> None: ...
    def get_total_xp(self, student_id: int) -> int: ...

class IBadgeRepository(Protocol):
    def grant_badge(self, student_id: int, badge_id: str) -> None: ...
    def has_badge(self, student_id: int, badge_id: str) -> bool: ...

class IGamificationRepository(Protocol):
    def get_completed_labs_count(self, student_id: int) -> int: ...