class BaseDomainException(Exception): pass
class ValidationError(BaseDomainException): pass
class InvalidCredentials(BaseDomainException): pass
class LabNotFound(BaseDomainException): pass
class LabNotFoundError(BaseDomainException): pass
class LabInstanceNotFoundError(BaseDomainException): pass
class StudentNotFoundError(BaseDomainException): pass
class InvalidFlag(BaseDomainException): pass
class ProgressAlreadyCompleted(BaseDomainException): pass
class UserAlreadyExists(BaseDomainException): pass
class InvalidProgressTransitionError(BaseDomainException): pass
class LabAlreadyCompletedError(BaseDomainException): pass