from typing import Protocol, Optional
from domain.entities.user import User

class IUserRepository(Protocol):
    def get_by_username(self, username: str) -> Optional[User]: ...
    def get_by_domain_id(self, domain_id: str) -> Optional[User]: ...
    def save(self, user: User) -> None: ...