from typing import Protocol

class UnitOfWork(Protocol):
    def __enter__(self) -> "UnitOfWork":
        ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        ...
    def commit(self) -> None:
        ...
    def rollback(self) -> None:
        ...